### ISSUE TITLE
Anonymization doesn't work when using MO2

### ISSUE THREAD

**Issue by foooooooooooooork** [blu3mania/npp-papyrus#16]
Compile works but anonymization fails with the message "no such file or directory".

**Comment by blu3mania** [comment]
I don't use MO2 myself but I know it is using VFS and you need to launch any executable that accesses Data folder through it. Are you launching Notepad++ from MO2? If not, you should try that. Though, if it's the case I am at a loss how PapyrusCompiler.exe is able to find psc file in the correct input folder an generate pex file in output folder...

**Comment by foooooooooooooork** [comment]
Yes Notepad++ is launched from MO2. It is very strange that the program can generate the correct pex file but anonymization fails... something about the VFS is interfering with the anonymization function but not the compile function?

**Comment by blu3mania** [comment]
I installed MO2 on another PC just to give this a try and I couldn't reproduce the issue. Can you check the newest usvfs log file under MO2's logs directory and see what you can find it in? The directory should be C:\Users\{USERNAME}\AppData\Local\ModOrganizer\Skyrim\logs if you are using default installation options.
