### ISSUE TITLE
NP++ crashing on versions after 8.2.1

### ISSUE THREAD

**Issue by dizietsma** [blu3mania/npp-papyrus#20]
Just updated to the latest NP++ 8.3.1 (64bit) and unless I disable the Papyrus Lexer plugin (by renaming the folder) NP++ crashes on launch, occasionally it doesn't crash but then when selecting a .psc file it then crashes.  When I go back to 8.2.1 all is fine
There is a comment in the NP++ forums regarding recompilation due to some change in how NP++ interfaces with plugins, is this relevant?
https://community.notepad-plus-plus.org/topic/22619/notepad-8-3-1-crashes-and-closes-without-warning

diziet

**Comment by blu3mania** [comment]
Confirmed. Checking in a fix now. 
Note that the new version will not work with Notepad++ v8.2.1 or older. WIll update documentation to have a warning.

**Comment by blu3mania** [comment]
@dizietsma I created release v0.3.0. Please give it a try and let me know if it solves your issue. You will need to manually install it. Thanks.

**Comment by dizietsma** [comment]
So far so good, hasn't crashed on loading the files it crashed on before.  Also hasn't crashed when opening NP++.

diziet

**Comment by blu3mania** [comment]
Thanks for the confirmation. I will close this issue then. Feel free to reopen or create a new report if you run into other issues.
