### ISSUE TITLE
SkyrimSE scripts compiling outside game directory

### ISSUE THREAD

**Issue by dizietsma** [blu3mania/npp-papyrus#54]
When compiling a script outside data/script/source (which I do accidentally all the time comparing one script with another!) the script is still compiled but into a 'scripts' subdirectory of the location of the psc file.
I'd like to have the option to turn this off (maybe with a notification when tried as well) or to have the pex file placed into the data/scripts directory that I have already specified in the settings for the plugin.
This is with SkyrimSE .

diziet

**Comment by blu3mania** [comment]
Ahhh! It's really a dumb miss from my end. Apparently the code never honors the selected compiler mode if it's not "Auto". So if you choose a different mode and restarts Notepad++, the option is reverted back to "Auto"...

I fixed it in the new release 1.2.1. You can grab from here: https://github.com/blu3mania/npp-papyrus/releases/tag/v1.2.1. Will get it included in next Notepad++ release. Now if you choose "Skyrim SE/AE" as compiler mode, all scripts, regardless where they are, will be compiled into your specified output directory.

Thanks for reporting this bug!

**Comment by dizietsma** [comment]
That was fast!  Thankyou:)

diziet
