### ISSUE TITLE
FO4 namespaces

### ISSUE THREAD

**Issue by dizietsma** [blu3mania/npp-papyrus#59]
Does the comment on the latest commit mean that I can now compile a script in user subfolder in FO4 without using a project file?
I could never get that to work before and gave up;  just put everything in ../source:)

diziet

**Comment by blu3mania** [comment]
Yes. For example, if you have a script "MyMOD:MyScript" in Data\Scripts\Source\User\MyMOD\MyScript.psc, v1.2.2 should be able to correctly compile (and optionally anonymize) it to Data\Scripts\MyMOD\MyScript.pex

**Comment by dizietsma** [comment]
Cwl:) I shall revisit my FO4 mods and see what happens!

diziet
